project:
  type: website
  output-dir: docs

website:
  title: "Joshana Shakya"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
      - href: projects.qmd
      - href: blog.qmd
      - href: cv.qmd
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/joshanashakya/
      - icon: github
        href: https://www.github.com/joshanashakya

format:
  html:
    theme:
      - pulse
    css: styles.css
    toc: true



